
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language: cpp

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - ./BreadthFirstSearch G_GermanCities.txt Frankfurt -s


